[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.install]
cmds = ["dotnet restore JobTrackerApi.csproj"]

[phases.build]
cmds = ["dotnet publish JobTrackerApi.csproj -c Release -o out"]

[start]
cmd = "dotnet out/JobTrackerApi.dll"